### PR TITLE
Update README to fix typos and make it easier to understand

### PR DESCRIPTION
**Pull request by simonsickle**

### CODE REVIEW

**Comment by simonsickle** [comment]
@niemyjski please let me know if you have any issues with this and I will update! Thanks

**Comment by niemyjski** [comment]
I think it looks good, currently on mobile.... Can you add back the screenshot to the readme?

**Comment by simonsickle** [comment]
My bad! I accidently removed it to reorganize the top a bit. It is back now

**Review by niemyjski — COMMENTED** [review]
LGTM, Thanks for the pr

**Comment by niemyjski** [comment]
@simonsickle can you please take a look at why the validate action is failing.

**Comment by simonsickle** [comment]
I'll try to give it a look this weekend!

**Pull request merged**
